M48
; DRILL file {KiCad 7.0.1} date Tue May 16 20:26:09 2023
; FORMAT={2:4/ absolute / inch / keep zeros}
; #@! TF.CreationDate,2023-05-16T20:26:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
%
G90
G05
T1
X024854Y-018350
T2
X028134Y-024650
X049866Y-018350
T0
M30
